### PR TITLE
Allow crafting of Amulet of Agile Fists

### PR DESCRIPTION
**Pull request by bfennema**
Add support for EnhancementLevelSquared to wondrous items (used for existing attack (mighty fists) and new agile enhancement).
Require agile/might fists to only be on neck.

### CODE REVIEW

**Comment by RobRendell** [comment]
Your changes look good!  I'll merge them in.  I'm also tempted to release what I have (since there are a few new enchantments that I never released).

I don't suppose you're interested in taking up the torch and continuing development of the CMI mod, are you?

**Comment by bfennema** [comment]
> Your changes look good! I'll merge them in. I'm also tempted to release what I have (since there are a few new enchantments that I never released).
> 
> I don't suppose you're interested in taking up the torch and continuing development of the CMI mod, are you?

Sure. 

I've been working on getting Oversized and Impact weapons modified to show up on the object using m_DamageDice instead of an Enchantment doing evt.IncreaseWeaponSize(). To prevent Lead Blades from stacking with Impact, I called evt.DecreaseWeaponSize() in the Impact enchantment whenever the player has the lead blade buffs to counteract that buff. Any thoughts on a cleaner way? Maybe the best way would be to patch Lead Blades to check for Impact before it calls evt.IncreaseWeaponSize, though I'm not sure how to go about doing that yet.

**Comment by RobRendell** [comment]
Oh, sorry!  I had a fix for that, but hadn't pushed it!  I just pushed it to the 1.10-kingmaker-2.0 branch now.

What I did was patch UIUtilityItem.FillWeaponDamage.  Reading Owlcat's code, I saw that they set  defaultWeaponStats.DoNotScaleDamage to true, which meant size-based increases were ignored.  I just set it back to false (and some other mucking around, which you can see in the commit diff).

What's your handle on NexusMods?  I'll start to set things up so you can edit the mod page and upload new versions.  Also, are you on the Kingmaker Discord server?

**Comment by bfennema** [comment]
My handle on NexusMods is blfennema.
I just logged on to the discord server for the first time a few minutes ago :)

**Comment by RobRendell** [comment]
Cool - I've added you, so you should be able to "Manage" the mod now.

Do you want to try to release the version 1.10.2 of the mod?  I would upload it as a pre-release version first, but it's up to you.

If you've forked the code from my GitHub, you'll want to update the Repository URL in info.json so UMM knows where to look for the latest version number.  UMM will check that file as it exists on GitHub as the current head of master, and report the mod as needing an update to users if the version goes up, so you should only push updates to Repository.json to master after you've actually uploaded a new version of the mod.  That's why I was working in a branch, which I could merge back into master at intervals when I published a new version.

**Comment by bfennema** [comment]
I will give uploading 1.10.2 a shot and see if I have any issues :)

**Comment by bfennema** [comment]
Do I need to set the ManagerVersion to the version of the UnityModManager.dll file I build the mod with? (its set to 0.14.1 but my dll is 0.21.4)

**Comment by RobRendell** [comment]
In my experience it seems pretty forgiving.  If UMM hasn't put anything about breaking changes in their release notes since 0.14.1, it should probably be fine.

**Pull request merged**
